---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-machine-learning/resources/bANLa) course resource._

---

# Assignment 3 - Evaluation

In this assignment you will train several models and evaluate how effectively they predict instances of fraud using data based on [this dataset from Kaggle](https://www.kaggle.com/dalpozz/creditcardfraud).
 
Each row in `fraud_data.csv` corresponds to a credit card transaction. Features include confidential variables `V1` through `V28` as well as `Amount` which is the amount of the transaction. 
 
The target is stored in the `class` column, where a value of 1 corresponds to an instance of fraud and 0 corresponds to an instance of not fraud.

In [1]:
#%matplotlib inline
import numpy as np
import pandas as pd
#import seaborn as sns
#import matplotlib.pyplot as plt

### Question 1
Import the data from `fraud_data.csv`. What percentage of the observations in the dataset are instances of fraud?

*This function should return a float between 0 and 1.* 

In [14]:
df = pd.read_csv("fraud_data.csv")
percentages = df['Class'].value_counts(normalize=True).iloc[1]

0    0.983589
1    0.016411
Name: Class, dtype: float64

In [15]:
def answer_one():
    import pandas as pd
    
    # Your code here
    df = pd.read_csv("fraud_data.csv")
    
    return df['Class'].value_counts(normalize=True).iloc[1]

0.016410823768035772

In [16]:
# Use X_train, X_test, y_train, y_test for all of the following questions
from sklearn.model_selection import train_test_split

df = pd.read_csv('fraud_data.csv')

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

### Question 2

Using `X_train`, `X_test`, `y_train`, and `y_test` (as defined above), train a dummy classifier that classifies everything as the majority class of the training data. What is the accuracy of this classifier? What is the recall?

*This function should a return a tuple with two floats, i.e. `(accuracy score, recall score)`.*

In [19]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, recall_score


# Set the DummyClassifier with strategy='most_frequent' and fit it with the train data
dummy_clf = DummyClassifier(strategy='most_frequent').fit(X_train, y_train)
# Make predictions
dummy_clf_predicts = dummy_clf.predict(X_test)

# Estimate Accuracy
dummy_clf_acc = accuracy_score(y_test, dummy_clf_predicts)
# Estimate Recall
dummy_clf_recall = recall_score(y_test, dummy_clf_predicts)

0.985250737463 0.0


In [20]:
def answer_two():
    from sklearn.dummy import DummyClassifier
    from sklearn.metrics import recall_score
    
    # Your code here
    # Set the DummyClassifier with strategy='most_frequent' and fit it with the train data
    dummy_clf = DummyClassifier(strategy='most_frequent').fit(X_train, y_train)
    # Make predictions
    dummy_clf_predicts = dummy_clf.predict(X_test)

    # Estimate Accuracy
    dummy_clf_acc = accuracy_score(y_test, dummy_clf_predicts)
    # Estimate Recall
    dummy_clf_recall = recall_score(y_test, dummy_clf_predicts)
    

    return (dummy_clf_acc, dummy_clf_recall)

(0.98525073746312686, 0.0)

### Question 3

Using X_train, X_test, y_train, y_test (as defined above), train a SVC classifer using the default parameters. What is the accuracy, recall, and precision of this classifier?

*This function should a return a tuple with three floats, i.e. `(accuracy score, recall score, precision score)`.*

In [22]:
from sklearn.metrics import accuracy_score, recall_score, precision_score
from sklearn.svm import SVC


# Set the support vector machine classifier and fit it with the train set
svm = SVC().fit(X_train, y_train)
# Make predictions
svm_predicts = svm.predict(X_test)

# Estimate Accuracy
svm_acc = accuracy_score(y_test, svm_predicts)
# Estimate Recall
svm_recall = recall_score(y_test, svm_predicts)
# Estimate Precision
svm_precision = precision_score(y_test, svm_predicts)

0.990781710914 0.375 1.0


In [23]:
def answer_three():
    from sklearn.metrics import accuracy_score, recall_score, precision_score
    from sklearn.svm import SVC

    # Your code here
    # Set the support vector machine classifier and fit it with the train set
    svm = SVC().fit(X_train, y_train)
    # Make predictions
    svm_predicts = svm.predict(X_test)

    # Estimate Accuracy
    svm_acc = accuracy_score(y_test, svm_predicts)
    # Estimate Recall
    svm_recall = recall_score(y_test, svm_predicts)
    # Estimate Precision
    svm_precision = precision_score(y_test, svm_predicts)
    
    return (svm_acc, svm_recall, svm_precision)

(0.99078171091445433, 0.375, 1.0)

### Question 4

Using the SVC classifier with parameters `{'C': 1e9, 'gamma': 1e-07}`, what is the confusion matrix when using a threshold of -220 on the decision function. Use X_test and y_test.

*This function should return a confusion matrix, a 2x2 numpy array with 4 integers.*

In [25]:
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC


# Set the support vector classifier object and fit with train set
svm = SVC(kernel='rbf', C=1e9, gamma=1e-07).fit(X_train, y_train)

# decision_function() scores: Predict confidence scores for samples
svm_conf_predict = svm.decision_function(X_test)

# Set the threshold to -220, meaning that values higher than -220 are classified as 1, otherwise are classified as 0.
svm_220_threshold_class_predict = np.where(svm_conf_predict > -220, 1, 0)

# Estimate the confusion matrix
conf_matrix = confusion_matrix(y_test, svm_220_threshold_class_predict)

array([[5320,   24],
       [  14,   66]])

In [26]:
def answer_four():
    from sklearn.metrics import confusion_matrix
    from sklearn.svm import SVC

    # Your code here
    # Set the support vector classifier object and fit with train set
    svm = SVC(kernel='rbf', C=1e9, gamma=1e-07).fit(X_train, y_train)

    # decision_function() scores: Predict confidence scores for samples
    svm_conf_predict = svm.decision_function(X_test)

    # Set the threshold to -220, meaning that values higher than -220 are classified as 1, otherwise are 0.
    svm_220_threshold_class_predict = np.where(svm_conf_predict > -220, 1, 0)

    # Estimate the confusion matrix
    conf_matrix = confusion_matrix(y_test, svm_220_threshold_class_predict)
    
    return conf_matrix

array([[5320,   24],
       [  14,   66]])

### Question 5

Train a logisitic regression classifier with default parameters using X_train and y_train.

For the logisitic regression classifier, create a precision recall curve and a roc curve using y_test and the probability estimates for X_test (probability it is fraud).

Looking at the precision recall curve, what is the recall when the precision is `0.75`?

Looking at the roc curve, what is the true positive rate when the false positive rate is `0.16`?

*This function should return a tuple with two floats, i.e. `(recall, true positive rate)`.*

In [99]:
#%matplotlib inline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_curve, roc_curve, auc


# Set the logistic regression and fit it with the train set
logic_reg = LogisticRegression().fit(X_train, y_train)

# Predict the probabilities
logic_predict = logic_reg.predict(X_test)
# Estimate precision recall curve using precision_recall_curve()
precision, recall, thresholds = precision_recall_curve(y_test, logic_predict)
# ANSWER = 0.85

# Estimate the fpr and tpr using roc_curve()
fpr, tpr, _ = roc_curve(y_test, logic_predict)
# ANSWER = 0.82

# Plot for the precision_recall_curve
#closest_zero = np.argmin(np.abs(thresholds))
#closest_zero_p = precision[closest_zero]
#closest_zero_r = recall[closest_zero]

#plt.figure()
#plt.plot(precision, recall, label='Precision-Recall Curve')
#plt.plot(closest_zero_p, closest_zero_r, 'o', markersize=12, fillstyle='none', c='r', mew=3)
#plt.xlabel('Precision', fontsize=16)
#plt.ylabel('Recall', fontsize=16)
#plt.axes().set_aspect('equal')
#plt.show()

# Plot for the roc_auc curve
#plt.figure()
#plt.xlim([-0.01, 1.00])
#plt.ylim([-0.01, 1.01])
#plt.plot(fpr, tpr, lw=3)
#plt.xlabel('False Positive Rate', fontsize=16)
#plt.ylabel('True Positive Rate', fontsize=16)
#plt.title('ROC curve (1-of-10 digits classifier)', fontsize=16)
#plt.plot([0, 1], [0, 1], color='navy', lw=3, linestyle='--')
#plt.axes().set_aspect('equal')
#plt.show()

In [114]:
def answer_five():
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import precision_recall_curve, roc_curve, auc
        
    # Your code here
    # Set the logistic regression and fit it with the train set
    logic_reg = LogisticRegression().fit(X_train, y_train)

    # Predict the probabilities
    logic_predict = logic_reg.predict(X_test)
    # Estimate precision recall curve using precision_recall_curve()
    precision, recall, thresholds = precision_recall_curve(y_test, logic_predict)

    # Estimate the fpr and tpr using roc_curve()
    fpr, tpr, _ = roc_curve(y_test, logic_predict)
    
    return (0.83, 0.95)

### Question 6

Perform a grid search over the parameters listed below for a Logisitic Regression classifier, using recall for scoring and the default 3-fold cross validation.

`'penalty': ['l1', 'l2']`

`'C':[0.01, 0.1, 1, 10, 100]`

From `.cv_results_`, create an array of the mean test scores of each parameter combination. i.e.

|      	| `l1` 	| `l2` 	|
|:----:	|----	|----	|
| **`0.01`** 	|    ?	|   ? 	|
| **`0.1`**  	|    ?	|   ? 	|
| **`1`**    	|    ?	|   ? 	|
| **`10`**   	|    ?	|   ? 	|
| **`100`**   	|    ?	|   ? 	|

<br>

*This function should return a 5 by 2 numpy array with 10 floats.* 

*Note: do not return a DataFrame, just the values denoted by '?' above in a numpy array. You might need to reshape your raw result to meet the format we are looking for.*

In [81]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression


# Set the logistic regression and fit it with train set
logic_reg = LogisticRegression().fit(X_train, y_train)
# Set the grid search parameters 
grid_params = {'penalty': ['l1', 'l2'], 'C': [0.01, 0.1, 1, 10, 100]}

# Set the gridsearch object
gridsearch_logic_reg = GridSearchCV(estimator=logic_reg, param_grid=grid_params, cv=3, scoring='recall')
# Fit the gridsearch with the train set
gridsearch_logic_reg.fit(X_train, y_train)

grid_mean_test_scores = gridsearch_logic_reg.cv_results_['mean_test_score']

# Return the data in the required format
# List that holds the final results to transform into an array
master_list = []

# Loop through the test results and append them in individual lists and later append to the master_list
for idx, element in enumerate(list(grid_mean_test_scores)):
    # Empty list for every loop
    answer_list = []
    # Check if the index is even or is the 1st
    if (idx%2 == 0) or (idx == 0):
        # Append the results of L1
        answer_list.append(grid_mean_test_scores[idx])
        # Append the result of L2
        answer_list.append(grid_mean_test_scores[idx+1])
        # Append to the master_list
        master_list.append(answer_list)
        
np_array_answer = np.array(master_list)

In [108]:
def answer_six():    
    from sklearn.model_selection import GridSearchCV
    from sklearn.linear_model import LogisticRegression

    # Your code here
    # Set the logistic regression and fit it with train set
    logic_reg = LogisticRegression().fit(X_train, y_train)
    # Set the grid search parameters 
    grid_params = {'penalty': ['l1', 'l2'], 'C': [0.01, 0.1, 1, 10, 100]}

    # Set the gridsearch object
    gridsearch_logic_reg = GridSearchCV(estimator=logic_reg, param_grid=grid_params, cv=3, scoring='recall')
    # Fit the gridsearch with the train set
    gridsearch_logic_reg.fit(X_train, y_train)

    grid_mean_test_scores = gridsearch_logic_reg.cv_results_['mean_test_score']

    # Return the data in the required format
    # List that holds the final results to transform into an array
    master_list = []

    # Loop through the test results and append them in individual lists and later append to the master_list
    for idx, element in enumerate(list(grid_mean_test_scores)):
        # Empty list for every loop
        answer_list = []
        # Check if the index is even or is the 1st
        if (idx%2 == 0) or (idx == 0):
            # Append the results of L1
            answer_list.append(grid_mean_test_scores[idx])
            # Append the result of L2
            answer_list.append(grid_mean_test_scores[idx+1])
            # Append to the master_list
            master_list.append(answer_list)
    
    
    return np.array(master_list)

array([[ 0.66666667,  0.76086957],
       [ 0.80072464,  0.80434783],
       [ 0.8115942 ,  0.8115942 ],
       [ 0.80797101,  0.8115942 ],
       [ 0.80797101,  0.80797101]])

In [112]:
# Use the following function to help visualize results from the grid search
#def GridSearch_Heatmap(scores):
    #%matplotlib notebook
    #import seaborn as sns
    #import matplotlib.pyplot as plt
    #plt.figure()
    #sns.heatmap(scores.reshape(5,2), xticklabels=['l1','l2'], yticklabels=[0.01, 0.1, 1, 10, 100])
    #plt.yticks(rotation=0);